config/routes.rb
Workarea::Admin::Engine.routes.draw do
  scope '(:locale)', constraints: Workarea::I18n.routes_constraint do
    resources :content_blogs do
      resources :comments, except: :new
      get :unsubscribe, to: 'comments#unsubscribe'

      get :create_entry, to: 'create_content_blog_entries#new'
      resources :blog_entries, controller: 'content_blog_entries', only: :index
    end

    # named to prevent conflict with nested (commentable) comments resource above
    resources :content_blog_comments, as: :content_blog_user_comments, only: %i[index edit update destroy]

    resources :content_blog_entries, only: %i[index show edit update destroy] do
      resources :comments, controller: 'content_blog_comments', only: :index

      member do
        get :thumbnail_image
        put :update_thumbnail_image
      end
    end

    resources :create_content_blog_entries, except: %i[index show] do
      member do
        get :thumbnail_image
        post :save_thumbnail_image

        get :content
        post :save_content

        get :featured_products

        get :publish
        post :save_publish
      end
    end
  end
end

Workarea::Storefront::Engine.routes.draw do
  scope '(:locale)', constraints: Workarea::I18n.routes_constraint do
    get 'blogs/:id/tagged/:tag', to: 'blogs#show', as: :blog_tagged

    resources :blogs, only: %i[index show]

    resources :blog_entries, only: :show do
      get 'comments', to: 'blog_comments#index', as: :comments
      post 'comment', to: 'blog_entries#add_comment'
    end
  end
end

app/models/workarea/search/admin/content_blog_entry.rb
module Workarea
  module Search
    class Admin
      class ContentBlogEntry < Search::Admin
        include Admin::Releasable

        def type
          'blog_entry'
        end

        def status
          if model.active?
            'active'
          else
            'inactive'
          end
        end

        def facets
          super.merge(blog_id: model.blog_id)
        end

        def jump_to_text
          model.name
        end

        def jump_to_position
          7
        end

        def search_text
          ['blog entry', model.name].flatten.join(' ')
        end
      end
    end
  end
end

app/controllers/workarea/admin/content_blog_entries_controller.rb
module Workarea
  module Admin
    class ContentBlogEntriesController < Admin::ApplicationController
      required_permissions :marketing
      before_action :find_blog_entry, except: :index

      def index
        query_params = if params[:content_blog_id].blank?
          params
        else
          blog = Content::Blog.find_by(slug: params[:content_blog_id])
          params.merge(blog_id: blog.id.to_s)
        end

        search = Search::AdminBlogEntries.new(query_params)
        @search = SearchViewModel.new(search, view_model_options)
        @blog = BlogViewModel.new(blog, view_model_options)
      end

      def show
        @blog_entry = BlogEntryViewModel.new(@blog_entry, params)
      end

      def edit
        @blog_entry = BlogEntryViewModel.new(@blog_entry, params)
      end

      def update
        if @blog_entry.update_attributes(params[:blog_entry])
          flash[:success] = t('workarea.admin.content_blog_entries.flash_messages.updated')
          redirect_to edit_content_blog_entry_path(@blog_entry)
        else
          @blog_entry = BlogEntryViewModel.new(@blog_entry, params)
          render :edit
        end
      end

      def thumbnail_image
        @blog_entry = BlogEntryViewModel.wrap(@blog_entry, params)
      end

      def update_thumbnail_image
        if @blog_entry.update_attributes(params[:blog_entry])
          flash[:success] = t('workarea.admin.content_blog_entries.flash_messages.updated')
          redirect_to thumbnail_image_content_blog_entry_path(@blog_entry)
        else
          @blog_entry = BlogEntryViewModel.wrap(@blog_entry, params)
          render :thumbnail_image
        end
      end

      def destroy
        @blog_entry.destroy
        flash[:success] = t('workarea.admin.content_blog_entries.flash_messages.deleted')
        redirect_to content_blog_blog_entries_path(content_blog_id: @blog_entry.blog)
      end

      private

      def find_blog_entry
        if params[:id].present?
          @blog_entry = Content::BlogEntry.find_by(slug: params[:id])
        else
          model = Content::Blog.find_by(slug: params[:content_blog_id])
          @blog_entry = model.entries.build(params[:blog_entry])
        end
      end
    end
  end
end

app/views/workarea/admin/content_blog_entries/_aux_navigation.html.haml
.grid.grid--auto.grid--right.grid--middle
  - if @blog_entry.present?
    .grid__cell= link_to t('workarea.admin.content_blog_entries.aux_navigation.view_blog'), content_blog_path(@blog_entry.blog)
  .grid__cell= link_to t('workarea.admin.actions.view_on_storefront'), storefront.blog_entry_path(model)

app/views/workarea/admin/content_blog_entries/_cards.html.haml
.grid.grid--auto.grid--flush.grid--center
  .grid__cell
    .card{ class: card_classes(:attributes, local_assigns[:active]) }
      = link_to edit_content_blog_entry_path(model), class: 'card__header' do
        %span.card__header-text= t('workarea.admin.content_blog_entries.cards.attributes.title')
        = inline_svg 'workarea/admin/icons/attributes.svg', class: 'card__icon'

      - if local_assigns[:active].blank?
        .card__body
          %ul.list-reset
            %li
              %strong= t('workarea.admin.content_blog_entries.cards.attributes.author')
              = model.author.titleize
            %li
              %strong= t('workarea.admin.content_blog_entries.cards.attributes.summary')
              = model.summary.presence || t('workarea.admin.content_blog_entries.cards.attributes.none')
            %li
              %strong= t('workarea.admin.content_blog_entries.cards.attributes.tags')
              = model.tags.join(', ').presence || t('workarea.admin.content_blog_entries.cards.attributes.none')
            %li
              %strong= t('workarea.admin.content_blog_entries.cards.attributes.featured')
              = model.featured.to_s.titleize
            %li
              %strong= t('workarea.admin.content_blog_entries.cards.attributes.written_at')
              = local_time(model.written_at)
            %li
              %strong= t('workarea.admin.fields.updated_at')
              #{local_time_ago(model.updated_at)}
            %li
              %strong= t('workarea.admin.content_blog_entries.cards.attributes.created')
              #{local_time_ago(model.created_at)}
          = link_to edit_content_blog_entry_path(model), class: 'card__button' do
            %span.button.button--small= t('workarea.admin.content_blog_entries.cards.attributes.button')

  .grid__cell
    .card{ class: card_classes(:thumbnail_image, local_assigns[:active]) }
      = link_to thumbnail_image_content_blog_entry_path(model), class: 'card__header' do
        %span.card__header-text= t('workarea.admin.content_blog_entries.cards.thumbnail_image.title')
        = inline_svg 'workarea/admin/icons/images.svg', class: 'card__icon'

      - if local_assigns[:active].blank?
        .card__body
          - if model.thumbnail_image.present?
            = image_tag(model.thumbnail_image_url)
            = link_to thumbnail_image_content_blog_entry_path(model), class: 'card__button' do
              %span.button.button--small= t('workarea.admin.content_blog_entries.cards.thumbnail_image.button_edit')
          - else
            .card__empty-note
              %p= t('workarea.admin.content_blog_entries.cards.thumbnail_image.no_thumbnail_image')
              %p= t('workarea.admin.content_blog_entries.cards.thumbnail_image.description')
            = link_to thumbnail_image_content_blog_entry_path(model), class: 'card__button' do
              %span.button.button--small= t('workarea.admin.content_blog_entries.cards.thumbnail_image.button_add')

  .grid__cell
    = render 'workarea/admin/content/card', content: model.content, active: local_assigns[:active]

  .grid__cell
    .card{ class: card_classes(:featured_products, local_assigns[:active]) }
      = link_to select_featured_product_path(model.to_global_id), class: 'card__header' do
        %span.card__header-text= t('workarea.admin.content_blog_entries.cards.featured_products.title')
        = inline_svg 'workarea/admin/icons/featured_products.svg', class: 'card__icon'

      - if local_assigns[:active].blank?
        .card__body
          - if model.featured_products.empty?
            .card__empty-note
              %p= t('workarea.admin.content_blog_entries.cards.featured_products.empty')
            %p= t('workarea.admin.content_blog_entries.cards.featured_products.description')
            = link_to select_featured_product_path(model.to_global_id), class: 'card__button' do
              %span.button.button--small= t('workarea.admin.content_blog_entries.cards.featured_products.empty_button')
          - else
            %ol.grid
              - model.featured_products.take(4).each_with_index do |product, i|
                %li.grid__cell.grid__cell--50
                  .card__photo-box
                    - if i == 3 && model.featured_products.size > 4
                      %span.card__photo +#{model.featured_products.size - i}
                    - else
                      = image_tag product_image_url(product.primary_image, :medium), alt: product.name, class: 'card__photo'
            = link_to edit_featured_product_path(model.to_global_id), class: 'card__button' do
              %span.button.button--small= t('workarea.admin.content_blog_entries.cards.featured_products.button')

  .grid__cell
    .card{ class: card_classes(:user_comments, local_assigns[:active]) }
      = link_to content_blog_entry_comments_path(content_blog_entry_id: model.slug), class: 'card__header' do
        %span.card__header-text= t('workarea.admin.content_blog_entries.cards.comments.title')
        = inline_svg 'workarea/admin/icons/comments.svg', class: 'card__icon'

      - if local_assigns[:active].blank?
        .card__body
          - if model.comments.present?
            .comments
              %ul.comments__comment-group
                - model.comments.take(3).each do |comment|
                  %li.comments__comment
                    .comments__comment-avatar
                      = avatar_for comment.author
                    .comments__comment-body
                      %span.comments__comment-author= comment.author.name
                      %span= comment.body
                      %span.comments__comment-time #{time_ago_in_words(comment.created_at)} ago

            = link_to content_blog_entry_comments_path(content_blog_entry_id: model.slug), class: 'card__button' do
              %span.button.button--small= t('workarea.admin.content_blog_entries.cards.comments.button_edit')
          - else
            %p= t('workarea.admin.content_blog_entries.cards.comments.no_comments')

            = link_to content_blog_user_comments_path(blog_entry_id: model.slug), class: 'card__button' do
              %span.button.button--small= t('workarea.admin.content_blog_entries.cards.comments.button_add')

  .grid__cell
    = render 'workarea/admin/timeline/card', timeline: model.timeline, active: local_assigns[:active]

app/views/workarea/admin/content_blog_entries/_summary.html.haml
= link_to content_blog_entry_path(model), class: 'summary' do
  %span.summary__type= t('workarea.admin.content_blog_entries.summary.blog_entry')
  %span.summary__name= model.name
  .summary__info-container
    - if model.written_at.present?
      %span.summary__info #{local_time(model.written_at)}
    - else
      %span.summary__info #{local_time(model.updated_at)}

    %span.summary__info= t('workarea.admin.content_blog_entries.summary.comments', count: model.comment_count)

app/views/workarea/admin/content_blog_entries/edit.html.haml
- @page_title = t('workarea.admin.content_blog_entries.edit.page_title', name: @blog_entry.name)

.view
  .view__header
    .grid.grid--middle
      .grid__cell.grid__cell--25
        = render 'workarea/admin/releases/select'
      .grid__cell.grid__cell--50
        .view__heading
          = link_to "↑ #{t('workarea.admin.content_blog_entries.show.index_link', name: @blog_entry.blog.name)}", content_blog_blog_entries_path(content_blog_id: @blog_entry.blog.slug), class: 'view__dashboard-button'
          %h1= link_to @blog_entry.name, url_for(@blog_entry)
      .grid__cell.grid__cell--25
        = render_aux_navigation_for(@blog_entry)

  .view__container
    = render_cards_for(@blog_entry, :attributes)

  .view__container.view__container--narrow

    - if @blog_entry.errors.present?
      = render 'workarea/admin/shared/errors', errors: @blog_entry.errors

    = form_tag content_blog_entry_path(@blog_entry), method: 'put', id: 'blog_entry_form', multipart: true do

      .section

        .property.property--required
          = label_tag 'blog_entry[name]', nil, class: 'property__name' do
            %span.property__text= t('workarea.admin.content_blog_entries.edit.name')
          = text_field_tag 'blog_entry[name]', @blog_entry.name, class: 'text-box text-box--i18n', required: true

        .property
          = label_tag 'blog_entry[tag_list]', nil, class: 'property__name' do
            %span.property__text= t('workarea.admin.fields.tags')
          = text_field_tag 'blog_entry[tag_list]', @blog_entry.tag_list, class: 'text-box'
          %span.property__note= t('workarea.admin.content_blog_entries.edit.tags_note')

        .property
          = label_tag 'blog_entry[slug]', t('workarea.admin.content_blog_entries.edit.slug_label'), class: 'property__name'
          %span= storefront.blog_entry_url('')
          = text_field_tag 'blog_entry[slug]', @blog_entry.slug, class: 'text-box text-box--medium', placeholder: @blog_entry.slug || 'your-slug-here', disabled: current_release.present?
          = render 'workarea/admin/shared/release_slug_tooltip'

        .property
          = label_tag 'blog_entry[author]', nil, class: 'property__name' do
            %span.property__text= t('workarea.admin.content_blog_entries.edit.author')
            %span.property__requirement *
          = text_field_tag 'blog_entry[author]', @blog_entry.author, class: 'text-box', required: true

        .property
          = label_tag 'blog_entry[summary]', nil, class: 'property__name' do
            %span.property__text= t('workarea.admin.content_blog_entries.edit.summary')
          = text_area_tag 'blog_entry[summary]', @blog_entry.summary, class: 'text-box text-box--multi-line'

        .grid
          .grid__cell.grid__cell--50-at-medium
            .property
              = label_tag 'blog_entry[written_at]', nil, class: 'property__name' do
                %span.property__text= t('workarea.admin.content_blog_entries.edit.date_written')
              = hidden_field_tag 'blog_entry[written_at]', @blog_entry.written_at, class: 'text-box', data: { datetimepicker_field: { inline: true }  }

        .grid.grid--hug
          .grid__cell.grid__cell--50.grid__cell--25-at-medium
            .compound-property
              %span.compound-property__name= t('workarea.admin.fields.active')
              = toggle_button_for 'blog_entry[active]', @blog_entry.active?

          .grid__cell.grid__cell--50.grid__cell--25-at-medium
            .compound-property
              %span.compound-property__name= t('workarea.admin.content_blog_entries.edit.featured')
              = toggle_button_for 'blog_entry[featured]', @blog_entry.featured

      .workflow-bar
        .grid.grid--auto.grid--right.grid--middle
          .grid__cell= render 'workarea/admin/shared/publishing_select'
          .grid__cell= button_tag t('workarea.admin.form.save_changes'), value: 'save_blog_entry', class: 'workflow-bar__button workflow-bar__button--update'

app/views/workarea/admin/content_blog_entries/index.html.haml
- @page_title = t('workarea.admin.content_blog_entries.index.entries_for', name: @blog.name)

.view
  .view__header
    .grid.grid--middle.grid--right
      .grid__cell.grid__cell--50
        .view__heading
          = link_to "↑ #{t('workarea.admin.content_blogs.edit.index_link')}", content_blogs_path, class: 'view__dashboard-button'
          %h1= link_to t('workarea.admin.content_blog_entries.index.entries_for', name: @blog.name), url_for(@blog)
      .grid__cell.grid__cell--25
        = render_aux_navigation_for(@blog)

  .view__container
    = render_cards_for(@blog, :blog_entries)

    .browsing-controls.browsing-controls--with-divider.browsing-controls--center
      = form_tag content_blog_blog_entries_path(content_blog_id: params[:content_blog_id]), method: 'get', id: 'blog_entry_search_form' do
        = facet_hidden_inputs(@search.facets)
        .browsing-controls__sort
          .property.property--inline
            = label_tag 'sort', t('workarea.admin.search.sort_by'), class: 'property__name'
            = select_tag :sort, options_for_select(@search.sorts, selected: @search.sort), data: { form_submitting_control: '' }

        .browsing-controls__search
          .search-form
            = text_field_tag :q, params[:q], class: 'search-form__input', id: 'search_categories', title: t('workarea.admin.search.keywords'), placeholder: t('workarea.admin.search.keywords')
            = submit_tag 'search_categories', class: 'search-form__button'

        = render 'workarea/admin/shared/creation_date', search: @search, form_path: catalog_categories_path

        - if @search.displayed_facets.present?
          - @search.displayed_facets.each do |facet|
            = render "workarea/admin/facets/#{facet.type}", facet: facet

        .browsing-controls__toggle-filters
          %button.text-button{ type: 'button', data: { toggle_filters: '' } }= t('workarea.admin.search.show_filters')

        - if @search.results.total_pages > 1
          .index-filters__row.hidden-if-js-enabled
            .index-filters__cell= render 'workarea/admin/shared/pagination', collection: @search.results

      %p.browsing-controls__count{ data: { browsing_controls_count: @search.total } }
        = pluralize(@search.total, 'blog content')

    - if @search.results.any?
      %table.index-table
        %thead
          %tr
            %th.index-table__control-cell
              .checkbox
                = check_box_tag 'select_all', nil, false, id: 'select_all', class: 'checkbox__input', data: { bulk_action_select_all: '' }
                = label_tag 'select_all', t('workarea.admin.bulk_actions.select_all'), class: 'checkbox__label'
            %th= t('workarea.admin.fields.name')
            %th= t('workarea.admin.content_blog_entries.fields.author')
            %th.align-center= t('workarea.admin.content_blog_entries.fields.featured')
            %th.align-center= t('workarea.admin.content_blog_entries.fields.comments')
            %th.align-center= t('workarea.admin.fields.content_blocks')
            %th= t('workarea.admin.fields.updated_at')
        %tbody
          - @search.results.each do |result|
            %tr.index-table__row{ class: ('index-table__row--inactive' unless result.active) }
              %td.index-table__control-cell
                .checkbox
                  = check_box_tag 'global_id', result.to_gid_param, false, class: 'checkbox__input', id: dom_id(result), data: { bulk_action_item: '' }
                  = label_tag dom_id(result), '', class: 'checkbox__label', title: t('workarea.admin.bulk_actions.add_summary_button')
              %td
                = link_to result.name, content_blog_entry_path(result)
                = upcoming_changesets_icon_for(result)
              %td= result.author.titleize
              %td.align-center= t("workarea.admin.#{result.featured}")
              %td.align-center= result.comments.count
              %td.align-center= result.content.blocks.count
              %td= local_time_ago(result.updated_at)

  .workflow-bar
    .grid
      .grid__cell.grid__cell--50
        = render 'workarea/admin/shared/bulk_actions', klass: Workarea::Content::BlogEntry, search: @search
      .grid__cell.grid__cell--50.align-right
        = link_to t('workarea.admin.content_blog_entries.index.new_blog_entry'), content_blog_create_entry_path(content_blog_id: @blog), id: 'add_blog_entry', class: 'workflow-bar__button workflow-bar__button--create'

app/views/workarea/admin/content_blog_entries/show.html.haml
- @page_title = @blog_entry.name
- @selected_navigation_nodes = ['Marketing', 'Blogs']

.view
  .view__header
    .grid.grid--middle
      .grid__cell.grid__cell--25
        = render 'workarea/admin/releases/select'
      .grid__cell.grid__cell--50
        .view__heading
          = link_to "↑ #{t('workarea.admin.content_blog_entries.show.index_link', name: @blog_entry.blog.name)}", content_blog_blog_entries_path(content_blog_id: @blog_entry.blog.slug), class: 'view__dashboard-button'
          %h1= @blog_entry.name
      .grid__cell.grid__cell--25
        = render_aux_navigation_for(@blog_entry)

  .view__container
    = render_cards_for(@blog_entry)

    .workflow-bar
      = link_to t('workarea.admin.actions.delete'), content_blog_entry_path(@blog_entry), class: 'workflow-bar__button workflow-bar__button--delete', data: { method: 'delete', confirm: t('workarea.admin.actions.delete_confirmation') }

app/views/workarea/admin/content_blog_entries/thumbnail_image.html.haml
- @page_title = t('workarea.admin.content_blog_entries.thumbnail_image.page_title', name: @blog_entry.name)

.view
  .view__header
    .grid.grid--middle
      .grid__cell.grid__cell--25
        = render 'workarea/admin/releases/select'
      .grid__cell.grid__cell--50
        .view__heading
          = link_to "↑ #{t('workarea.admin.content_blog_entries.thumbnail_image.index_link', name: @blog_entry.blog.name)}", content_blog_blog_entries_path(content_blog_id: @blog_entry.blog.slug)
          %h1= link_to @blog_entry.name, url_for(@blog_entry)
      .grid__cell.grid__cell--25
        = render_aux_navigation_for(@blog_entry)

  .view__container
    = render_cards_for(@blog_entry, :thumbnail_image)

  .view__container.view__container--narrow

    - if @blog_entry.errors.present?
      = render 'workarea/admin/shared/errors', errors: @blog_entry.errors

    = form_tag update_thumbnail_image_content_blog_entry_path(@blog_entry), method: 'put', id: 'blog_entry_form', multipart: true do
      .section
        %h2= t('workarea.admin.content_blog_entries.thumbnail_image.thumbnail_image')
        - if @blog_entry.has_thumbnail_image?
          %table.data-pairs
            %tbody
              %tr
                %th
                  %span.data-pairs__name= t('workarea.admin.content_blog_entries.thumbnail_image.current_image')
                %td= link_to image_tag(@blog_entry.thumbnail_image_url, alt: t('workarea.admin.content_blog_entries.thumbnail_image.view_thumbnail_image')), @blog_entry.thumbnail_image_url, target: '_blank'

        .property
          = label_tag 'blog_entry[thumbnail_image]', class: 'property__name' do
            %span.property__text= t('workarea.admin.content_blog_entries.thumbnail_image.choose_image_file')

          .asset-picker-field{ data: { asset_picker_field: '' } }
            .asset-picker-field__cell
              = hidden_field_tag "blog_entry[thumbnail_image]", @blog_entry[:thumbnail_image], class: 'text-box text-box--i18n'

              %span{ data: { asset_name: true } }
                - asset = Workarea::Content::Asset.find_or_initialize_by(id: @blog_entry[:thumbnail_image])
                = asset.name.presence || t('workarea.admin.content_blocks.asset.name_missing')

            .asset-picker-field__cell= link_to t('workarea.admin.content_blocks.asset.select_an_asset'), insert_content_assets_path(file_type: 'image'), class: 'text-button', data: { asset_picker_field_open: '', turbolinks: false }
            - if asset.name.present?
              .asset-picker-field__cell= button_tag t('workarea.admin.content_blocks.asset.clear_asset'), type: 'button', value: 'clear_asset', id: 'clear_asset', class: 'text-button text-button--destroy', data: { asset_picker_field_clear: '' }

          %span.property__note= t('workarea.admin.content_blog_entries.thumbnail_image.asset_input_note')

      .workflow-bar
        .grid.grid--auto.grid--right.grid--middle
          .grid__cell= render 'workarea/admin/shared/publishing_select'
          .grid__cell= button_tag t('workarea.admin.form.save_changes'), value: 'save_blog_entry', class: 'workflow-bar__button workflow-bar__button--update'