config/routes.rb
Workarea::Admin::Engine.routes.draw do
  scope '(:locale)', constraints: Workarea::I18n.routes_constraint do
    resources :content_blogs do
      resources :comments, except: :new
      get :unsubscribe, to: 'comments#unsubscribe'

      get :create_entry, to: 'create_content_blog_entries#new'
      resources :blog_entries, controller: 'content_blog_entries', only: :index
    end

    # named to prevent conflict with nested (commentable) comments resource above
    resources :content_blog_comments, as: :content_blog_user_comments, only: %i[index edit update destroy]

    resources :content_blog_entries, only: %i[index show edit update destroy] do
      resources :comments, controller: 'content_blog_comments', only: :index

      member do
        get :thumbnail_image
        put :update_thumbnail_image
      end
    end

    resources :create_content_blog_entries, except: %i[index show] do
      member do
        get :thumbnail_image
        post :save_thumbnail_image

        get :content
        post :save_content

        get :featured_products

        get :publish
        post :save_publish
      end
    end
  end
end

Workarea::Storefront::Engine.routes.draw do
  scope '(:locale)', constraints: Workarea::I18n.routes_constraint do
    get 'blogs/:id/tagged/:tag', to: 'blogs#show', as: :blog_tagged

    resources :blogs, only: %i[index show]

    resources :blog_entries, only: :show do
      get 'comments', to: 'blog_comments#index', as: :comments
      post 'comment', to: 'blog_entries#add_comment'
    end
  end
end

app/controllers/workarea/admin/create_content_blog_entries_controller.rb
module Workarea
  module Admin
    class CreateContentBlogEntriesController < Admin::ApplicationController
      required_permissions :marketing
      before_action :find_blog_entry

      def new
        @blog = Admin::BlogViewModel.new(Workarea::Content::Blog.find_by(slug: params[:content_blog_id]))
        render :setup
      end

      def create
        @blog_entry.attributes = params[:blog_entry]

        if @blog_entry.save
          flash[:success] = t('workarea.admin.create_content_blog_entries.flash_messages.blog_entry_created')
          redirect_to thumbnail_image_create_content_blog_entry_path(@blog_entry)
        else
          render :setup, status: :unprocessable_entity
        end
      end

      def thumbnail_image
        render :thumbnail_image
      end

      def save_thumbnail_image
        @blog_entry.update_attributes(params[:blog_entry])
        redirect_to content_create_content_blog_entry_path(@blog_entry)
      end

      def content
        model = Content.for(@blog_entry.model)
        @content = Admin::ContentViewModel.new(model, view_model_options)
      end

      def featured_products
        search = Search::AdminProducts.new(view_model_options)
        @search = SearchViewModel.new(search, view_model_options)
      end

      def publish; end

      def save_publish
        publish = SavePublishing.new(@blog_entry, params)

        if publish.perform
          flash[:success] = t('workarea.admin.create_content_blog_entries.flash_messages.blog_entry_created')
          redirect_to content_blog_entry_path(@blog_entry)
        else
          flash[:error] = publish.errors.full_messages
          render :publish
        end
      end

      private

      def find_blog_entry
        model = if params[:id].present?
          Content::BlogEntry.find_by(slug: params[:id])
        else
          Content::BlogEntry.new(blog_id: params[:content_blog_id])
        end

        @blog_entry = Admin::BlogEntryViewModel.new(model, view_model_options)
      end
    end
  end
end

app/views/workarea/admin/create_content_blog_entries/content.html.haml
- @page_title = t('workarea.admin.create_content_blog_entries.content.page_title', name: @blog_entry.name)

.view
  .view__header
    .view__heading
      %h1= t('workarea.admin.create_content_blog_entries.content.title', name: @blog_entry.name)

  .view__container

    = render 'workarea/admin/content/edit', content: @content, workflow: true

    .workflow-bar
      .grid.grid--middle
        .grid__cell.grid__cell--20
          = link_to t('workarea.admin.form.cancel'), content_blog_entry_path(@blog_entry), class: 'workflow-bar__button workflow-bar__button--delete', data: { method: 'delete', confirm: t('workarea.admin.create_content_blog_entries.workflow.cancel_message') }

        .grid__cell.grid__cell--60
          %ol.workflow-bar__steps
            %li
              %li 1) #{link_to t('workarea.admin.create_content_blog_entries.workflow.steps.setup'), create_content_blog_entry_path(@blog_entry)}
              %li 2) #{link_to t('workarea.admin.create_content_blog_entries.workflow.steps.thumbnail_image'), thumbnail_image_create_content_blog_entry_path(@blog_entry)}
              %strong 3) #{ t('workarea.admin.create_content_blog_entries.workflow.steps.content')}
              %li 4) #{link_to t('workarea.admin.create_content_blog_entries.workflow.steps.featured_products'), featured_products_create_content_blog_entry_path(@blog_entry)}
              %li 5) #{link_to t('workarea.admin.create_content_blog_entries.workflow.steps.publish'), publish_create_content_blog_entry_path(@blog_entry)}

        .grid__cell.grid__cell--20
          .grid.grid--auto.grid--right.grid--middle
            .grid__cell= link_to t('workarea.admin.create_content_blog_entries.content.button'), featured_products_create_content_blog_entry_path(@blog_entry), class: 'workflow-bar__button'

app/views/workarea/admin/create_content_blog_entries/featured_products.html.haml
- @page_title = t('workarea.admin.create_content_blog_entries.featured_products.page_title', name: @blog_entry.name)

.view
  .view__header
    .view__heading
      %h1.heading.heading--no-margin= t('workarea.admin.create_content_blog_entries.featured_products.title', name: @blog_entry.name)
      %p= link_to t('workarea.admin.create_content_blog_entries.workflow.skip_this'), content_blog_create_entry_path(@blog_entry)

  .view__container
    .section
      %p.align-center= t('workarea.admin.create_content_blog_entries.featured_products.instruction')

      .browsing-controls.browsing-controls--with-divider.browsing-controls--center{ class: ('browsing-controls--filters-displayed' unless @search.toggle_facets?) }
        = form_tag featured_products_create_content_blog_entry_path(@blog_entry), method: 'get', id: 'product_search_form' do
          = facet_hidden_inputs(@search.facets)
          .browsing-controls__sort
            .property.property--inline
              = label_tag 'sort', t('workarea.admin.search.sort_by'), class: 'property__name'
              = select_tag :sort, options_for_select(@search.sorts, selected: @search.sort), data: { form_submitting_control: '' }

          .browsing-controls__search
            .search-form
              = text_field_tag :q, params[:q], class: 'search-form__input', title: t('workarea.admin.search.keywords'), placeholder: t('workarea.admin.search.keywords')
              = submit_tag 'search_products', class: 'search-form__button'

          = render 'workarea/admin/shared/creation_date', search: @search, form_path: featured_products_create_content_blog_entry_path(@blog_entry)

          - if @search.facets.present?
            - @search.facets.each do |facet|
              = render "workarea/admin/facets/#{facet.type}", facet: facet

          -if @search.toggle_facets?
            .browsing-controls__toggle-filters
              %button.text-button{ type: 'button', data: { toggle_filters: '' } }= t('workarea.admin.search.show_filters')

        = render 'workarea/admin/facets/applied', search: @search, reset_path: featured_products_create_content_blog_entry_path(@blog_entry)

    - if @search.results.blank?
      %h2
        = t('workarea.admin.create_content_blog_entries.featured_products.no_matching_products')
        = link_to t('workarea.admin.create_content_blog_entries.featured_products.start_over'), featured_products_create_content_blog_entry_path(@blog_entry)

    - else
      .grid.grid--auto.grid--flush.grid--center
        - @search.results.each do |result|
          .grid__cell
            - if @blog_entry.product_ids.include?(result.id)
              = render 'workarea/admin/featured_products/selected', featurable: @blog_entry, product: result
            - else
              = render 'workarea/admin/featured_products/unselected', featurable: @blog_entry, product: result

      - if @search.results.total_pages > 1
        = render 'workarea/admin/shared/pagination', collection: @search.results

  .workflow-bar
    .grid.grid--middle
      .grid__cell.grid__cell--20
        = link_to t('workarea.admin.form.cancel'), content_blog_entry_path(@blog_entry), class: 'workflow-bar__button workflow-bar__button--delete', data: { method: 'delete', confirm: t('workarea.admin.create_content_blog_entries.workflow.cancel_message') }

      .grid__cell.grid__cell--60
        %ol.workflow-bar__steps
          %li.workflow-bar__step 1) #{link_to t('workarea.admin.create_content_blog_entries.workflow.steps.setup'), create_content_blog_entry_path(@blog_entry)}
          %li.workflow-bar__step 2) #{link_to t('workarea.admin.create_content_blog_entries.workflow.steps.thumbnail_image'), thumbnail_image_create_content_blog_entry_path(@blog_entry)}
          %li.workflow-bar__step 3) #{link_to t('workarea.admin.create_content_blog_entries.workflow.steps.content'), content_create_content_blog_entry_path(@blog_entry)}
          %li.workflow-bar__step
            %strong 4) #{t('workarea.admin.create_content_blog_entries.workflow.steps.featured_products')}
          %li.workflow-bar__step 5) #{link_to t('workarea.admin.create_content_blog_entries.workflow.steps.publish'), publish_create_content_blog_entry_path(@blog_entry)}

      .grid__cell.grid__cell--20
        .grid.grid--auto.grid--right.grid--middle
          .grid__cell= link_to "#{t('workarea.admin.create_content_blog_entries.featured_products.button')} →", publish_create_content_blog_entry_path(@blog_entry), class: 'workflow-bar__button'

app/views/workarea/admin/create_content_blog_entries/publish.html.haml
- @page_title = t('workarea.admin.create_content_blog_entries.publish.page_title', name: @blog_entry.name)

.view
  .view__header
    .view__heading
      %h1= t('workarea.admin.create_content_blog_entries.publish.title', name: @blog_entry.name)

  .view__container
    = form_tag save_publish_create_content_blog_entry_path(@blog_entry), method: 'post' do
      .section
        .grid.grid--center
          .grid__cell.grid__cell--40-at-medium
            .publish-create-release{ data: { publish_create_release: '' } }
              .property
                = radio_button_tag 'activate', 'now', current_release.blank?, title: 'Active'
                = label_tag 'activate_now', 'Now', class: 'heading--4'

              - release_options.each do |release|
                .property
                  = radio_button_tag 'activate', release.id, release == current_release, title: 'Active'
                  = label_tag "activate_#{release.id}", "With #{release.name}", class: 'heading--4'

              .property
                = radio_button_tag 'activate', 'new_release', params[:activate] == 'new_release', title: 'Active'
                = label_tag 'activate_new_release', 'With a new release:', class: 'heading--4'

              .publish-create-release__fields.hidden
                .property
                  = label_tag 'release[name]', 'Release name', class: 'property__name'
                  = text_field_tag 'release[name]', nil, class: 'text-box text-box--wide', placeholder: "Mother's Day #{Time.now.year}"
                .property
                  = label_tag 'release[publish_at]', 'When does it publish?', class: 'property__name'
                  = hidden_field_tag 'release[publish_at]', nil, placeholder: 'When does it publish?', data: { datetimepicker_field: { inline: true } }

      .workflow-bar
        .grid.grid--middle
          .grid__cell.grid__cell--20
            = link_to t('workarea.admin.form.cancel'), content_blog_entry_path(@blog_entry), class: 'workflow-bar__button workflow-bar__button--delete', data: { method: 'delete', confirm: t('workarea.admin.create_content_blog_entries.workflow.cancel_message') }

          .grid__cell.grid__cell--60
            %ol.workflow-bar__steps
              %li
                %li 1) #{link_to t('workarea.admin.create_content_blog_entries.workflow.steps.setup'), create_content_blog_entry_path(@blog_entry)}
                %li 2) #{link_to t('workarea.admin.create_content_blog_entries.workflow.steps.thumbnail_image'), thumbnail_image_create_content_blog_entry_path(@blog_entry)}
                %li 3) #{link_to t('workarea.admin.create_content_blog_entries.workflow.steps.content'), content_create_content_blog_entry_path(@blog_entry)}
                %li 4) #{link_to t('workarea.admin.create_content_blog_entries.workflow.steps.featured_products'), featured_products_create_content_blog_entry_path(@blog_entry)}
                %strong 5) #{t('workarea.admin.create_content_blog_entries.workflow.steps.publish')}

          .grid__cell.grid__cell--20
            .grid.grid--auto.grid--right.grid--middle
              .grid__cell= button_tag t('workarea.admin.create_content_blog_entries.publish.button'), class: 'workflow-bar__button'

app/views/workarea/admin/create_content_blog_entries/setup.html.haml
- @page_title = t('workarea.admin.create_content_blog_entries.setup.page_title')
- @breadcrumbs = ['Marketing', 'Blog']

.view
  .view__header
    .view__heading
      %h1= t('workarea.admin.create_content_blog_entries.setup.title')

  .view__container.view__container--narrow
    - @blog_entry.errors.full_messages.each do |message|
      = render_message 'error', message

    = form_tag create_content_blog_entries_path, method: 'post' do
      = hidden_field_tag :id, @blog_entry.slug unless @blog_entry.new_record?
      = hidden_field_tag 'blog_entry[active]', false
      = hidden_field_tag 'blog_entry[blog_id]', @blog.id

      .section
        .property.property--required
          = label_tag 'blog_entry_name', t('workarea.admin.create_content_blog_entries.setup.name_label'), class: 'property__name'
          = text_field_tag 'blog_entry[name]', @blog_entry.name, class: 'text-box text-box--i18n', required: true

        .property.property--required
          = label_tag 'blog_entry_author', t('workarea.admin.create_content_blog_entries.setup.author_label'), class: 'property__name'
          = text_field_tag 'blog_entry[author]', @blog_entry.author || current_user.name, class: 'text-box text-box--i18n', required: true

        .property
          = label_tag 'blog_entry_summary', t('workarea.admin.create_content_blog_entries.summary.summary_label'), class: 'property__name'
          = text_area_tag 'blog_entry[summary]', @blog_entry.summary, class: 'text-box text-box--i18n text-box--multi-line'

        .property
          = label_tag 'blog_entry[tag_list]', t('workarea.admin.fields.tags'), class: 'property__name'
          = text_field_tag 'blog_entry[tag_list]', @blog_entry.tag_list, class: 'text-box'
          %span.property__note= t('workarea.admin.form.csv_field_note')

      .workflow-bar
        .grid.grid--middle
          .grid__cell.grid__cell--20
            - if @blog_entry.new_record?
              = link_to t('workarea.admin.form.cancel'), content_blog_blog_entries_path, class: 'workflow-bar__button workflow-bar__button--delete'
            - else
              = link_to t('workarea.admin.form.cancel'), content_blog_entries_path(@blog_entry), class: 'workflow-bar__button workflow-bar__button--delete', data: { method: 'delete', confirm: t('workarea.admin.create_content_blog_entries.workflow.cancel_message') }

          .grid__cell.grid__cell--60
            %ol.workflow-bar__steps
              %li
                %strong 1) #{t('workarea.admin.create_content_blog_entries.workflow.steps.setup')}
              - if @blog_entry.new_record?
                %li 2) #{t('workarea.admin.create_content_blog_entries.workflow.steps.thumbnail_image')}
                %li 3) #{t('workarea.admin.create_content_blog_entries.workflow.steps.content')}
                %li 4) #{t('workarea.admin.create_content_blog_entries.workflow.steps.featured_products')}
                %li 5) #{t('workarea.admin.create_content_blog_entries.workflow.steps.publish')}
              - else
                %li 2) #{link_to t('workarea.admin.create_content_blog_entries.workflow.steps.thumbnail_image'), thumbnail_image_create_content_blog_entry_path(@blog_entry)}
                %li 3) #{link_to t('workarea.admin.create_content_blog_entries.workflow.steps.content'), content_create_content_blog_entry_path(@blog_entry)}
                %li 4) #{link_to t('workarea.admin.create_content_blog_entries.workflow.steps.featured_products'), featured_products_create_content_blog_entry_path(@blog_entry)}
                %li 5) #{link_to t('workarea.admin.create_content_blog_entries.workflow.steps.publish'), publish_create_content_blog_entry_path(@blog_entry)}

          .grid__cell.grid__cell--20
            .grid.grid--auto.grid--right.grid--middle
              .grid__cell= button_tag t('workarea.admin.create_content_blog_entries.setup.button'), value: 'save_setup', class: 'workflow-bar__button workflow-bar__button--create'

app/views/workarea/admin/create_content_blog_entries/thumbnail_image.html.haml
- @page_title = t('workarea.admin.create_content_blog_entries.thumbnail_image.page_title', name: @blog_entry.name)

.view
  .view__header
    .view__heading
      %h1= t('workarea.admin.create_content_blog_entries.thumbnail_image.title', name: @blog_entry.name)

  .view__container.view__container--narrow
    - @blog_entry.errors.full_messages.each do |message|
      = render_message 'error', message

    = form_tag save_thumbnail_image_create_content_blog_entry_path(@blog_entry), method: 'post' do
      = hidden_field_tag :id, @blog_entry.slug unless @blog_entry.new_record?
      = hidden_field_tag 'blog_entry[active]', false

      .property
        = label_tag 'blog_entry[thumbnail_image]', class: 'property__name' do
          %span.property__text Choose Image File

        .asset-picker-field{ data: { asset_picker_field: '' } }
          .asset-picker-field__cell
            = hidden_field_tag "blog_entry[thumbnail_image]", @blog_entry[:thumbnail_image], class: 'text-box text-box--i18n'

            %span{ data: { asset_name: true } }
              - asset = Workarea::Content::Asset.find_or_initialize_by(id: @blog_entry[:thumbnail_image])
              = asset.name.presence || t('workarea.admin.content_blocks.asset.name_missing')

          .asset-picker-field__cell= link_to t('workarea.admin.content_blocks.asset.select_an_asset'), insert_content_assets_path(file_type: 'image'), class: 'text-button', data: { asset_picker_field_open: '', turbolinks: false }
          - if asset.name.present?
            .asset-picker-field__cell= button_tag t('workarea.admin.content_blocks.asset.clear_asset'), type: 'button', value: 'clear_asset', id: 'clear_asset', class: 'text-button text-button--destroy', data: { asset_picker_field_clear: '' }

      .workflow-bar
        .grid.grid--middle
          .grid__cell.grid__cell--20
            = link_to t('workarea.admin.form.cancel'), content_blog_entry_path(@blog_entry), class: 'workflow-bar__button workflow-bar__button--delete', data: { method: 'delete', confirm: t('workarea.admin.create_content_blog_entries.workflow.cancel_message') }

          .grid__cell.grid__cell--60
            %ol.workflow-bar__steps
              %li
                %li 1) #{link_to t('workarea.admin.create_content_blog_entries.workflow.steps.setup'), create_content_blog_entry_path(@blog_entry)}
                %strong 2) #{t('workarea.admin.create_content_blog_entries.workflow.steps.thumbnail_image')}
                %li 3) #{link_to t('workarea.admin.create_content_blog_entries.workflow.steps.content'), content_create_content_blog_entry_path(@blog_entry)}
                %li 4) #{link_to t('workarea.admin.create_content_blog_entries.workflow.steps.featured_products'), featured_products_create_content_blog_entry_path(@blog_entry)}
                %li 5) #{link_to t('workarea.admin.create_content_blog_entries.workflow.steps.publish'), publish_create_content_blog_entry_path(@blog_entry)}

          .grid__cell.grid__cell--20
            .grid.grid--auto.grid--right.grid--middle
              .grid__cell= button_tag t('workarea.admin.create_content_blog_entries.thumbnail_image.button'), value: 'save_setup', class: 'workflow-bar__button workflow-bar__button--create'