config/routes.rb
Workarea::Admin::Engine.routes.draw do
  scope '(:locale)', constraints: Workarea::I18n.routes_constraint do
    resources :content_blogs do
      resources :comments, except: :new
      get :unsubscribe, to: 'comments#unsubscribe'

      get :create_entry, to: 'create_content_blog_entries#new'
      resources :blog_entries, controller: 'content_blog_entries', only: :index
    end

    # named to prevent conflict with nested (commentable) comments resource above
    resources :content_blog_comments, as: :content_blog_user_comments, only: %i[index edit update destroy]

    resources :content_blog_entries, only: %i[index show edit update destroy] do
      resources :comments, controller: 'content_blog_comments', only: :index

      member do
        get :thumbnail_image
        put :update_thumbnail_image
      end
    end

    resources :create_content_blog_entries, except: %i[index show] do
      member do
        get :thumbnail_image
        post :save_thumbnail_image

        get :content
        post :save_content

        get :featured_products

        get :publish
        post :save_publish
      end
    end
  end
end

Workarea::Storefront::Engine.routes.draw do
  scope '(:locale)', constraints: Workarea::I18n.routes_constraint do
    get 'blogs/:id/tagged/:tag', to: 'blogs#show', as: :blog_tagged

    resources :blogs, only: %i[index show]

    resources :blog_entries, only: :show do
      get 'comments', to: 'blog_comments#index', as: :comments
      post 'comment', to: 'blog_entries#add_comment'
    end
  end
end

app/models/workarea/search/admin/content_blog.rb
module Workarea
  module Search
    class Admin
      class ContentBlog < Search::Admin
        def type
          'blog'
        end

        def status
          'active'
        end

        def jump_to_text
          model.name
        end

        def jump_to_position
          6
        end

        def search_text
          ['blog', model.name, model.entries.map(&:name)].flatten.join(' ')
        end
      end
    end
  end
end

app/controllers/workarea/admin/content_blogs_controller.rb
module Workarea
  module Admin
    class ContentBlogsController < Admin::ApplicationController
      required_permissions :marketing
      before_action :find_blog, except: :index

      def index
        search = Search::AdminBlogs.new(
          params.merge(autocomplete: request.xhr?)
        )
        @search = BlogSearchViewModel.new(search, params)
      end

      def show; end

      def create
        if @blog.save
          flash[:success] = 'Blog has been created'
          redirect_to edit_content_blog_path(@blog)
        else
          render :new
        end
      end

      def update
        if @blog.update_attributes(blog_params)
          flash[:success] = 'Blog has been updated'
          redirect_to edit_content_blog_path(@blog)
        else
          render :edit
        end
      end

      def destroy
        @blog.destroy
        flash[:success] = 'This blog has been removed'
        redirect_to content_blogs_path
      end

      private

      def find_blog
        @blog = if params[:id].present?
          BlogViewModel.new(Workarea::Content::Blog.find_by(slug: params[:id]))
        else
          BlogViewModel.new(Workarea::Content::Blog.new(blog_params))
        end
      end

      def blog_params
        return {} unless params[:blog].present?
        params[:blog].permit(:name, :slug, :navigation)
      end
    end
  end
end

app/views/workarea/admin/content_blogs/_aux_navigation.html.haml
.grid.grid--auto.grid--right.grid--middle
  .grid__cell= link_to t('workarea.admin.actions.view_on_storefront'), storefront.blog_path(model)

app/views/workarea/admin/content_blogs/_cards.html.haml
.grid.grid--auto.grid--flush.grid--center
  .grid__cell
    .card{ class: card_classes(:attributes, local_assigns[:active]) }
      = link_to edit_content_blog_path(model), class: 'card__header' do
        %span.card__header-text= t('workarea.admin.content_blogs.cards.attributes.title')
        = inline_svg 'workarea/admin/icons/attributes.svg', class: 'card__icon'

      - if local_assigns[:active].blank?
        .card__body
          %ul.list-reset
            %li
              %strong= t('workarea.admin.content_blogs.cards.attributes.entries')
              = model.entries.count
            %li
              %strong= t('workarea.admin.content_blogs.cards.attributes.navigation')
              = model.navigation.to_s.titleize
            %li
              %strong= t('workarea.admin.content_blogs.cards.attributes.modified')
              #{local_time_ago(model.updated_at)}
            %li
              %strong= t('workarea.admin.content_blogs.cards.attributes.created')
              #{local_time_ago(model.created_at)}
          = link_to edit_content_blog_path(model), class: 'card__button' do
            %span.button.button--small=  t('workarea.admin.content_blogs.cards.attributes.button')

  .grid__cell
    .card{ class: card_classes(:blog_entries, local_assigns[:active]) }
      = link_to content_blog_blog_entries_path(content_blog_id: model.slug), class: 'card__header' do
        %span.card__header-text= t('workarea.admin.content_blogs.cards.blog_entries.title')
        = inline_svg 'workarea/admin/blog/icons/blog_entry.svg', class: 'card__icon'

      - if local_assigns[:active].blank?
        .card__body
          - if model.entries.empty?
            .card__empty-note
              %p= t('workarea.admin.content_blogs.cards.blog_entries.empty')
            = link_to create_content_blog_entries_path(content_blog_id: model), class: 'card__button' do
              %span.button.button--small= t('workarea.admin.content_blogs.cards.blog_entries.button_create')
          - else
            %ul.list-reset
              - model.entries.take(10).each_with_index do |entry, i|
                %li
                  %p
                    = entry.name
                    %br
                    = t('workarea.admin.content_blogs.cards.blog_entries.by', author: entry.author)

          = link_to content_blog_blog_entries_path(content_blog_id: model.slug), class: 'card__button' do
            %span.button.button--small= t('workarea.admin.content_blogs.cards.blog_entries.button')

  .grid__cell
    = render 'workarea/admin/content/card', content: model.content, active: local_assigns[:active]

  .grid__cell
    = render 'workarea/admin/timeline/card', timeline: model.timeline, active: local_assigns[:active]

  .grid__cell
    = render 'workarea/admin/comments/card', commentable: model, active: local_assigns[:active]

app/views/workarea/admin/content_blogs/_summary.html.haml
= link_to content_blog_path(model), class: 'summary' do
  %span.summary__type= t('workarea.admin.content_blogs.summary.type')
  %span.summary__name= model.name
  .summary__info-container
    %span.summary__info #{local_time_ago(model.updated_at)}
    %span.summary__info= t('workarea.admin.content_blogs.summary.entries', count: model.entries.count)

app/views/workarea/admin/content_blogs/edit.html.haml
- @page_title = t('workarea.admin.content_blogs.edit.page_title', name: @blog.name)

.view
  .view__header
    .grid.grid--middle
      .grid__cell.grid__cell--25
        = render 'workarea/admin/releases/select'
      .grid__cell.grid__cell--50
        .view__heading
          = link_to "↑ #{t('workarea.admin.content_blogs.edit.index_link')}", content_blogs_path, class: 'view__dashboard-button'
          %h1= link_to t('workarea.admin.content_blogs.edit.page_title', name: @blog.name), url_for(@blog)
      .grid__cell.grid__cell--25
        = render_aux_navigation_for(@blog)

  .view__container
    = render_cards_for(@blog, :attributes)

  .view__container.view__container--narrow

    - if @blog.errors.present?
      = render 'workarea/admin/shared/errors', errors: @blog.errors

    = form_tag content_blog_path(@blog), method: 'put', id: 'blog_form' do
      .section
        .property
          = label_tag 'blog_name', nil, class: 'property__name' do
            %span.property__text= t('workarea.admin.content_blogs.edit.name')
            %span.property__requirement *
          = text_field_tag 'blog[name]', @blog.name, class: 'text-box text-box--i18n', required: true
        .property
          = label_tag 'blog_slug', nil, class: 'property__name' do
            %span.property__text= t('workarea.admin.content_blogs.edit.page_url')

          %span= storefront.blog_url('')
          = text_field_tag 'blog[slug]', @blog.slug, class: 'text-box text-box--medium', placeholder: @blog.slug || 'your-slug-here', disabled: current_release.present?
          %span.property__note= t('workarea.admin.content_blogs.edit.page_url_note')
          = render 'workarea/admin/shared/release_slug_tooltip'

        .grid
          .grid__cell.grid__cell--50.grid__cell--25-at-medium
            .property
              = label_tag 'blog_updated_at', t('workarea.admin.fields.updated_at'), class: 'property__name'
              = local_time(@blog.updated_at)
          .grid__cell.grid__cell--50.grid__cell--25-at-medium
            .property
              = label_tag 'blog_created_at', t('workarea.admin.fields.created_at'), class: 'property__name'
              = local_time(@blog.created_at)

      .workflow-bar
        .grid.grid--auto.grid--right.grid--middle
          .grid__cell= render 'workarea/admin/shared/publishing_select'
          .grid__cell= button_tag 'Save changes', value: 'save_blog', class: 'workflow-bar__button workflow-bar__button--update'

app/views/workarea/admin/content_blogs/index.html.haml
- @page_title = t('workarea.admin.content_blogs.index.title')

.view
  .view__header
    .grid.grid--middle.grid--center
      .grid__cell.grid__cell--50
        .view__heading
          = link_to "↑ #{t('workarea.admin.content_blogs.index.dashboard_link')}", root_path, class: 'view__dashboard-button'
          %h1= t('workarea.admin.content_blogs.index.title')

  .view__container
    .browsing-controls.browsing-controls--with-divider.browsing-controls--center
      = form_tag content_blogs_path, method: 'get', id: 'blog_search_form' do
        = facet_hidden_inputs(@search.facets)
        .browsing-controls__sort
          .property.property--inline
            = label_tag 'sort', t('workarea.admin.search.sort_by'), class: 'property__name'
            = select_tag :sort, options_for_select(@search.sorts, selected: @search.sort), data: { form_submitting_control: '' }

        .browsing-controls__search
          .search-form
            = text_field_tag :q, params[:q], class: 'search-form__input', id: 'search_categories', title: t('workarea.admin.search.keywords'), placeholder: t('workarea.admin.search.keywords')
            = submit_tag 'search_categories', class: 'search-form__button'

        = render 'workarea/admin/shared/creation_date', search: @search, form_path: catalog_categories_path

        - if @search.facets.present?
          - @search.facets.each do |facet|
            = render "workarea/admin/facets/#{facet.type}", facet: facet

        .browsing-controls__toggle-filters
          %button.text-button{ type: 'button', data: { toggle_filters: '' } }= t('workarea.admin.search.show_filters')

        - if @search.facet_selections.any?
          = render 'workarea/admin/facets/applied', search: @search, reset_path: catalog_categories_path

      %p.browsing-controls__count{ data: { browsing_controls_count: @search.total } }
        = pluralize(@search.total, 'blog')

    - if @search.results.any?
      %table.index-table
        %thead
          %tr
            %th.index-table__control-cell
              .checkbox
                = check_box_tag 'select_all', nil, false, id: 'select_all', class: 'checkbox__input', data: { bulk_action_select_all: '' }
                = label_tag 'select_all', t('workarea.admin.bulk_actions.select_all'), class: 'checkbox__label'
            %th= t('workarea.admin.fields.name')
            %th.align-center= t('workarea.admin.content_blogs.fields.entries')
            %th= t('workarea.admin.content_blogs.fields.navigation')
            %th= t('workarea.admin.fields.updated_at')
        %tbody
          - @search.results.each do |result|
            %tr.index-table__row
              %td.index-table__control-cell
                .checkbox
                  = check_box_tag 'global_id', result.to_gid_param, false, class: 'checkbox__input', id: dom_id(result), data: { bulk_action_item: '' }
                  = label_tag dom_id(result), '', class: 'checkbox__label', title: t('workarea.admin.bulk_actions.add_summary_button')
              %td
                = link_to result.name, content_blog_path(result)
                = upcoming_changesets_icon_for(result)
                = comments_icon_for(result)
              %td.align-center= result.entries.count
              %td
                - unless result.navigation.blank?
                  = result.navigation.to_s.titleize
                - else
                  = t('workarea.admin.content_blogs.cards.attributes.no_navigation')
              %td= local_time_ago(result.created_at)

  .workflow-bar
    .grid
      .grid__cell.grid__cell--50
        = render 'workarea/admin/shared/bulk_actions', klass: Workarea::Content::Blog, search: @search
      .grid__cell.grid__cell--50.align-right
        = link_to t('workarea.admin.content_blogs.index.button'), new_content_blog_path, id: 'add_blog', class: 'workflow-bar__button workflow-bar__button--create'

app/views/workarea/admin/content_blogs/new.html.haml
- @page_title = t('workarea.admin.content_blogs.new.page_title')

.view
  .view__header
    .grid.grid--middle
      .grid__cell.grid__cell--25
        = render 'workarea/admin/releases/select'
      .grid__cell.grid__cell--50
        .view__heading
          = link_to t('workarea.admin.content_blogs.new.blogs'), content_blogs_path
          %h1= t('workarea.admin.content_blogs.new.title')

  - if @blog.errors.present?
    = render 'workarea/admin/shared/errors', errors: @blog.errors

  .view__container.view__container--narrow
    = form_tag content_blogs_path, method: 'post', id: 'blog_form' do
      .section
        .property.property--required
          = label_tag 'blog_name', nil, class: 'property__name' do
            %span.property__text= t('workarea.admin.content_blogs.new.name')
          = text_field_tag 'blog[name]', @blog.name, class: 'text-box text-box--i18n', required: true
        .property
          = label_tag 'blog_slug', nil, class: 'property__name' do
            %span.property__text= t('workarea.admin.content_blogs.new.page_url')
          %span= storefront.blog_url('')
          = text_field_tag 'blog[slug]', @blog[:slug], class: 'text-box text-box--medium', placeholder: @blog[:slug] || 'your-slug-here'
          %span.property__note= t('workarea.admin.content_blogs.new.page_url_note')

      .workflow-bar
        .grid.grid--auto.grid--right.grid--middle
          .grid__cell= render 'workarea/admin/shared/publishing_select'
          .grid__cell= button_tag t('workarea.admin.content_blogs.new.create_blog'), value: 'save_blog', class: 'workflow-bar__button workflow-bar__button--create'

app/views/workarea/admin/content_blogs/show.html.haml
- @page_title = @blog.name

.view
  .view__header
    .grid.grid--middle
      .grid__cell.grid__cell--25
        = render 'workarea/admin/releases/select'
      .grid__cell.grid__cell--50
        .view__heading
          = link_to_index_for(@blog)
          %h1= @blog.name
      .grid__cell.grid__cell--25
        = render_aux_navigation_for(@blog)

  .view__container
    = render_cards_for(@blog)

    .workflow-bar
      = link_to t('workarea.admin.actions.delete'), content_blog_path(@blog), class: 'workflow-bar__button workflow-bar__button--delete', data: { method: 'delete', confirm: t('workarea.admin.content_blogs.actions.delete_confirmation') }