config/routes.rb
Workarea::Admin::Engine.routes.draw do
  scope '(:locale)', constraints: Workarea::I18n.routes_constraint do
    resources :content_blogs do
      resources :comments, except: :new
      get :unsubscribe, to: 'comments#unsubscribe'

      get :create_entry, to: 'create_content_blog_entries#new'
      resources :blog_entries, controller: 'content_blog_entries', only: :index
    end

    # named to prevent conflict with nested (commentable) comments resource above
    resources :content_blog_comments, as: :content_blog_user_comments, only: %i[index edit update destroy]

    resources :content_blog_entries, only: %i[index show edit update destroy] do
      resources :comments, controller: 'content_blog_comments', only: :index

      member do
        get :thumbnail_image
        put :update_thumbnail_image
      end
    end

    resources :create_content_blog_entries, except: %i[index show] do
      member do
        get :thumbnail_image
        post :save_thumbnail_image

        get :content
        post :save_content

        get :featured_products

        get :publish
        post :save_publish
      end
    end
  end
end

Workarea::Storefront::Engine.routes.draw do
  scope '(:locale)', constraints: Workarea::I18n.routes_constraint do
    get 'blogs/:id/tagged/:tag', to: 'blogs#show', as: :blog_tagged

    resources :blogs, only: %i[index show]

    resources :blog_entries, only: :show do
      get 'comments', to: 'blog_comments#index', as: :comments
      post 'comment', to: 'blog_entries#add_comment'
    end
  end
end

app/controllers/workarea/admin/content_blog_comments_controller.rb
module Workarea
  module Admin
    class ContentBlogCommentsController < Admin::ApplicationController
      required_permissions :marketing
      before_action :find_blog_comment, except: :index

      def index
        options = params.merge(built_sort: find_sort(Content::BlogComment))
        @blog_comments = Admin::BlogCommentsViewModel.new(nil, options)
      end

      def edit; end

      def update
        if @blog_comment.update_attributes(blog_comment_params)
          flash[:success] = 'Blog entry comment has been updated'
          redirect_to content_blog_user_comments_path(
            content_blog_entry_id: params[:content_blog_entry_id]
          )
        else
          render :edit
        end
      end

      def destroy
        @blog_comment.destroy
        flash[:success] = t('workarea.admin.content_blogs_comments.flash_messages.destroyed')
        redirect_to content_blog_user_comments_path
      end

      private

      def find_blog_comment
        if params[:id].present?
          @blog_comment = Content::BlogComment.find(params[:id])

          @user = User.where(id: @blog_comment.user_id).first
        end
      end

      def new_admin_comment_params
        params[:comment].permit(:body).merge(
          user_id: current_user.id,
          user_info: current_user.public_info
        )
      end

      def blog_comment_params
        return {} if params[:blog_comment].blank?
        params[:blog_comment].permit(:body, :pending, :approved)
      end
    end
  end
end

app/views/workarea/admin/content_blog_comments/_summary.html.haml
%li.comments__comment
  .comments__comment-header
    .comments__comment-avatar
      = link_to user_path(model.author) do
        = avatar_for model.author, additional_css_class: 'avatar'
    %h3.comments__comment-author= link_to model.author.name, user_path(model.author)
    %p.comments__comment-time
      #{time_ago_in_words(model.created_at)} ago
      - if model.pending
        = t('workarea.admin.content_blogs_comments.summary.pending')
    .comments__comment-actions
      .grid.grid--auto
        .grid__cell
          = link_to edit_content_blog_user_comment_path(model), class: 'text-button' do
            %span.grid.grid--auto.grid--middle
              %span.grid__cell= t('workarea.admin.actions.edit')
              %span.grid__cell= inline_svg('workarea/admin/icons/edit.svg', class: 'text-button__icon')
        .grid__cell
          = link_to content_blog_user_comment_path(model), class: 'text-button text-button--destroy', remote: true, data: { method: 'delete' } do
            %span.grid.grid--auto.grid--middle
              %span.grid__cell= t('workarea.admin.actions.delete')
              %span.grid__cell= inline_svg('workarea/admin/icons/delete.svg', class: 'text-button__icon')
        - if model.pending?
          .grid__cell
            = link_to content_blog_user_comment_path(model), class: 'text-button text-button--create', remote: true, data: { method: 'put', params: { 'blog_comment[approved]' => true } } do
              %span.grid.grid--auto.grid--middle
                %span.grid__cell= t('workarea.admin.content_blogs_comments.index.approve')
                %span.grid__cell= inline_svg('workarea/admin/icons/recommendations.svg', class: 'text-button__icon')
          .grid__cell
            = link_to content_blog_user_comment_path(model), class: 'text-button text-button--destroy', remote: true, data: { method: 'put', params: { 'blog_comment[approved]' => false } } do
              %span.grid.grid--auto.grid--middle
                %span.grid__cell= t('workarea.admin.content_blogs_comments.index.deny')
                %span.grid__cell= inline_svg('workarea/admin/icons/close.svg', class: 'text-button__icon')

  .comments__comment-body
    %p= model.body

app/views/workarea/admin/content_blog_comments/edit.html.haml
- @page_title = t('workarea.admin.content_blogs_comments.edit.page_title', name: @blog_comment.entry.name)

.view
  .view__header
    .grid.grid--middle
      .grid__cell.grid__cell--100
        .view__heading
          = link_to t('workarea.admin.content_blogs_comments.edit.comments_for_name', name: @blog_comment.entry.name), content_blog_user_comments_path(blog_entry_id: @blog_comment.entry.slug)
          %h1= t('workarea.admin.content_blogs_comments.edit.edit_comment_by_user', user_name: @blog_comment.author.name)

  .view__container
    = render_cards_for(@blog_comment, :attributes)

    - if @blog_comment.errors.present?
      = render 'workarea/admin/shared/errors', errors: @blog_comment.errors

  .view__container.view__container--narrow
    = form_tag content_blog_user_comment_path(@blog_comment), method: 'put', id: 'blog_comment_form' do
      = hidden_field_tag 'blog_entry_id', params[:blog_entry_id] if params[:blog_entry_id].present?

      .grid.grid--middle
        .grid__cell.grid__cell--75-at-medium
          .comments
            .comments__comment-header
              .comments__comment-avatar
                = link_to user_path(@blog_comment.author) do
                  = avatar_for @blog_comment.author, additional_css_class: 'avatar'
              - if @user.present?
                %h3.comments__comment-author= link_to @blog_comment.author.name, user_path(@blog_comment.author)
              - else
                %h3.comments__comment-author= t('workarea.admin.content_blogs_comments.edit.unregistered_user')

        .grid__cell.grid__cell--25-at-medium
          .grid.grid--auto.grid--right.grid--middle
            .grid__cell
              .compound-property
                %span.compound-property__name= t('workarea.admin.content_blogs_comments.edit.approved')
                = toggle_button_for 'blog_comment[approved]', @blog_comment.approved

      .property.property--stacked
        = label_tag 'blog_comment_body', t('workarea.admin.content_blogs_comments.edit.comment'), class: 'property__name'
        = text_area_tag 'blog_comment[body]', @blog_comment.body, class: 'text-box text-box--multi-line'

      .grid.grid--huge
        .grid__cell.grid__cell--50.grid__cell--25-at-medium
          .property
            = label_tag 'comment_updated_at', t('workarea.admin.fields.updated_at'), class: 'property__name'
            = local_time(@blog_comment.updated_at)
        .grid__cell.grid__cell--50.grid__cell--25-at-medium
          .property
            = label_tag 'comment_created_at', t('workarea.admin.fields.created_at'), class: 'property__name'
            = local_time(@blog_comment.created_at)

      .workflow-bar
        .grid.grid--middle
          .grid__cell.grid__cell--50-at-medium
            = link_to t('workarea.admin.form.cancel'), :back, class: 'workflow-bar__button workflow-bar__button--delete'
          .grid__cell.grid__cell--50-at-medium
            .grid.grid--auto.grid--right.grid--middle
              .grid__cell= button_tag t('workarea.admin.form.save_changes'), value: 'save_blog_comment', class: 'workflow-bar__button workflow-bar__button--update'

app/views/workarea/admin/content_blog_comments/index.html.haml
- @page_title = t('workarea.admin.content_blogs_comments.index.page_title')

.view.comments
  .view__header
    .grid.grid--right.grid--middle
      .grid__cell.grid__cell--50
        .view__heading
          - if @blog_comments.blog_entry.present?
            = link_to t('workarea.admin.content_blogs_comments.index.dashboard_link', blog_name: @blog_comments.blog_entry.blog.name), content_blog_blog_entries_path(@blog_comments.blog_entry.blog.slug)
          - else
            = link_to t('workarea.admin.content_blogs_comments.index.all_blogs'), content_blogs_path
          - if @blog_comments.blog_entry.present?
            %h1= link_to t('workarea.admin.content_blogs_comments.index.comments_for_entry', entry_name: @blog_comments.blog_entry.name), url_for(@blog_comments.blog_entry)
          - else
            %h1= t('workarea.admin.content_blogs_comments.index.blog_entry_comments')
      .grid__cell.grid__cell--25
        - if @blog_comments.blog_entry.present?
          = render_aux_navigation_for(@blog_comments.blog_entry)

  .view__container.view__container--narrow
    - if @blog_comments.comments.empty?
      %p= t('workarea.admin.content_blogs_comments.index.no_comments_found')

    - else
      - form_path = @blog_comments.blog_entry.present? ? content_blog_user_comments_path(content_blog_entry_id: @blog_comments.blog_entry) : content_blog_user_comments_path
      = form_tag form_path, method: 'get', id: 'blog_comments_sort_form' do
        = hidden_field_tag 'content_blog_entry_id', params[:content_blog_entry_id] if params[:content_blog_entry_id].present?

        .browsing-controls.browsing-controls--with-divider.browsing-controls--center
          .property.property--inline
            = label_tag 'sort', t('workarea.admin.search.sort_by'), class: 'property__name'
            = select_tag 'sort', options_for_select(sort_options(@blog_comments), params[:sort]), data: { form_submitting_control: '' }

          %p.browsing-controls__count{ data: { browsing_controls_count: @blog_comments.comments.total_count } }
            = t('workarea.admin.content_blogs_comments.index.comments', count: @blog_comments.comments.total_count)

      .section
        .comments__comment-group
          - @blog_comments.comments.each do |blog_comment|
            = render_summary_for(blog_comment)

      - if @blog_comments.comments.total_pages > 1
        = render 'workarea/admin/shared/pagination', collection: @blog_comments.comments

      .workflow-bar
        .grid
          .grid__cell.grid__cell--50
            .grid.grid--auto
              .grid__cell= link_to t('workarea.admin.shared.bulk_actions.import'), new_data_file_import_path(model_type: Workarea::Content::BlogComment, return_to: form_path), class: 'workflow-bar__button'
              .grid__cell= link_to t('workarea.admin.shared.bulk_actions.export'), new_data_file_export_path(model_type: Workarea::Content::BlogComment, query_id: generic_admin_search_query_id(model_type: Workarea::Content::BlogComment, entry_id: @blog_comments&.blog_entry&.id), return_to: form_path), class: 'workflow-bar__button'